### ISSUE TITLE
No explicit way of handling foreign keys in attribute groups

### ISSUE THREAD

**Issue by trickvi** [openspending/osep#19] opened 2015-07-09 15:44 UTC
There needs to be an explicit way for attribute groups to work across different datasets. For example, the payer attribute group will in a normalised set up have an id in the budget resource which is a foreign key to an id in another resource which contains the title and perhaps the description. It's not clear how this should be handled and it needs to be explicit.

**Comment by pwalsh** [comment] 2015-07-09 15:47
@tryggvib there are examples of this in OSEP-04:

http://labs.openspending.org/osep/osep-04.html#example-with-entities-normalized

It is explicit at the JTS level, but I agree it is not in the mapping (that is why I have the comments there saying "note: we really want a way of saying this has been dereferenced!").

**Comment by rufuspollock** [comment] 2015-07-10 11:16
I wonder if the mapping should be to the main "physical" table i.e. in that table the mapping of payor should be the entities table. I get that that may be sort of confusing though. I guess it is whether you think you are mapping transactions or just to the logical target tables - if the latter than mapping the entities csv makes more sense.

**Comment by rufuspollock** [comment] 2015-08-17 14:55
I'm thinking we always maps dimensions against the main table - so if stuff is normalized out you go against that and use foreign key info to add the relevant column to the fact table.

**Comment by rufuspollock** [comment] 2015-11-03 17:08
DUPLICATE of https://github.com/openspending/fiscal-data-package/issues/49

**Closed as completed by rufuspollock** 2015-11-03 17:08 UTC
