### ISSUE TITLE
Difficult parsing of foreign keys: a proposal to make it easier

### ISSUE THREAD

**Issue by marek-dudas** [openspending/osep#28] opened 2015-08-07 09:27 UTC
The fact that there is no explicit way of saying (directly in the mapping) that a property is mapped to different table and referenced through a foreign key has been already posted as an issue. Here is a preliminary proposal, how to make it explicit:
- each property that maps to different resource than the one where amount is mapped to (mapping.amount.resource) must have properties _sourceKey_ and _targetKey_
- targetKey: name of the field in resource containing primary key
- sourceKey: name of the field in _mapping.amount.resource_ with key referencing to the target resource 

See more details and examples in https://goo.gl/1HSZSk (Proposal 4).

**Comment by rufuspollock** [comment] 2015-11-03 17:08
DUPLICATE of https://github.com/openspending/fiscal-data-package/issues/49 (I think)

**Closed as completed by rufuspollock** 2015-11-03 17:08 UTC
